/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package drugmacy;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.*;
import drugmacy.Package.*;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author nurka
 */
public class AdminPage extends javax.swing.JFrame {

    private Pegawai pegawai;
    private Obat obat;
    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        pegawai = new Pegawai();
        obat = new Obat();
        initComponents();
        tampilkan();
    }
    
    class JPanelGradient extends javax.swing.JPanel
    {
        protected void paintComponent(Graphics g)
        {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
            
            Color color1 = new Color(0, 51, 102);
            Color color2 = new Color(0, 204, 153);
            GradientPaint gp = new GradientPaint(0, 0, color1, width, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanelGradient();
        jLabel6 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        panePage = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField_nama = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField_alamat = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField_contact = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField_password = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataPegawaiTable = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        editIdPegawaiField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        editAlamatPegawaiField = new javax.swing.JTextField();
        editNamaPegawaiField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        editContactPegawaiField = new javax.swing.JTextField();
        cancelPegawaiButton = new javax.swing.JButton();
        deletePegawaiButton = new javax.swing.JButton();
        updatePegawaiButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        editPasswordPegawaiField = new javax.swing.JTextField();
        editUsernamePegawaiField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        searchPegawaiField = new javax.swing.JTextField();
        refreshButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jTextField_id3 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField_namaobat = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField_harga = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField_stok = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataObatTable = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        editIdObatField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        editNamaObatField = new javax.swing.JTextField();
        editHargaObatField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        editStokObatField = new javax.swing.JTextField();
        cancelObatButton = new javax.swing.JButton();
        deleteObatButton = new javax.swing.JButton();
        updateObatButton = new javax.swing.JButton();
        searchObatButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        searchObatField = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Page");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pegawai.png"))); // NOI18N
        jLabel6.setText("Data Pegawai");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Drug.png"))); // NOI18N
        jLabel30.setText("Data Obat");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Drug.png"))); // NOI18N
        jLabel31.setText("Input Obat");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rumah.png"))); // NOI18N
        jLabel32.setText("Home");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pegawai.png"))); // NOI18N
        jLabel33.setText("Input Pegawai");
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel30)
                    .addComponent(jLabel6)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 800));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setText("Welcome");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AW.png"))); // NOI18N
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jButton1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 539, 190, 77));

        panePage.addTab("tab1", jPanel2);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel2.setText("Input Pegawai");

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel20.setText("Id Pegawai (Contoh : 100)");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 8, -1, -1));
        jPanel10.add(jTextField_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 37, 285, 30));

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel21.setText("Nama");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 71, -1));
        jPanel10.add(jTextField_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 285, 30));

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel22.setText("Alamat");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel10.add(jTextField_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 285, 30));

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel23.setText("Contact");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 71, -1));
        jPanel10.add(jTextField_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 285, 30));

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel24.setText("Username");

        jTextField_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usernameActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel25.setText("Password");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_password)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(0, 193, Short.MAX_VALUE))
                    .addComponent(jTextField_username))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jButton16.setText("Insert");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("Clear");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AW.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(155, 155, 155))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(229, 229, 229))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(116, 116, 116))
        );

        panePage.addTab("tab2", jPanel3);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel12.setText("Data Pegawai");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        dataPegawaiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "Alamat", "Kontak", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataPegawaiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataPegawaiTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dataPegawaiTable);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 428, 674, 360));

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel13.setText("Id Pegawai (Contoh : 100)");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 8, -1, -1));

        editIdPegawaiField.setEnabled(false);
        jPanel9.add(editIdPegawaiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 37, 285, 30));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel14.setText("Alamat");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 85, -1, -1));

        editAlamatPegawaiField.setEnabled(false);
        jPanel9.add(editAlamatPegawaiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 114, 285, 30));

        editNamaPegawaiField.setEnabled(false);
        jPanel9.add(editNamaPegawaiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 37, 285, 30));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel15.setText("Nama");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 8, 71, -1));

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel16.setText("Contact");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 85, 71, -1));

        editContactPegawaiField.setEnabled(false);
        jPanel9.add(editContactPegawaiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 114, 285, 30));

        cancelPegawaiButton.setText("Cancel");
        cancelPegawaiButton.setEnabled(false);
        cancelPegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPegawaiButtonActionPerformed(evt);
            }
        });
        jPanel9.add(cancelPegawaiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 91, 30));

        deletePegawaiButton.setText("Delete");
        deletePegawaiButton.setEnabled(false);
        deletePegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePegawaiButtonActionPerformed(evt);
            }
        });
        jPanel9.add(deletePegawaiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 91, 30));

        updatePegawaiButton.setText("Update");
        updatePegawaiButton.setEnabled(false);
        updatePegawaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePegawaiButtonActionPerformed(evt);
            }
        });
        jPanel9.add(updatePegawaiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 91, 30));

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel18.setText("Password");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 100, -1));

        editPasswordPegawaiField.setEnabled(false);
        jPanel9.add(editPasswordPegawaiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 285, 30));

        editUsernamePegawaiField.setEnabled(false);
        jPanel9.add(editUsernamePegawaiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 285, 30));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel19.setText("Username");
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 84, 670, 270));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel7.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 91, 30));

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel17.setText("Id Pegawai");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 110, 30));
        jPanel7.add(searchPegawaiField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 170, 30));

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        jPanel7.add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 91, 30));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panePage.addTab("tab3", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel3.setText("Input Obat");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 6, -1, -1));

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel26.setText("Id Obat (Contoh : AAA)");
        jPanel12.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 8, -1, -1));
        jPanel12.add(jTextField_id3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 37, 530, 30));

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel27.setText("Nama Obat");
        jPanel12.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, -1));
        jPanel12.add(jTextField_namaobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 530, 30));

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel28.setText("Harga");
        jPanel12.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel12.add(jTextField_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 530, 30));

        jLabel29.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel29.setText("Stok");
        jPanel12.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 71, -1));
        jPanel12.add(jTextField_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 530, 30));

        jPanel5.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 350, 584, 329));

        jButton18.setText("Insert");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 697, 110, 45));

        jButton19.setText("Clear");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 697, 110, 45));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Obat2.png"))); // NOI18N
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        panePage.addTab("tab4", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel5.setText("Data Obat");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        dataObatTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "Harga", "Stok"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataObatTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataObatTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataObatTable);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 348, 674, 440));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("Id Obat (Contoh : AAA)");

        editIdObatField.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setText("Nama Obat");

        editNamaObatField.setEnabled(false);

        editHargaObatField.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel9.setText("Harga");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel10.setText("Stok");

        editStokObatField.setEnabled(false);

        cancelObatButton.setText("Cancel");
        cancelObatButton.setEnabled(false);
        cancelObatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelObatButtonActionPerformed(evt);
            }
        });

        deleteObatButton.setText("Delete");
        deleteObatButton.setEnabled(false);
        deleteObatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteObatButtonActionPerformed(evt);
            }
        });

        updateObatButton.setText("Update");
        updateObatButton.setEnabled(false);
        updateObatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateObatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(editIdObatField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(editNamaObatField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editHargaObatField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editStokObatField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(updateObatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelObatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteObatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editIdObatField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editHargaObatField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editNamaObatField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editStokObatField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelObatButton, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(updateObatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteObatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 84, -1, 200));

        searchObatButton.setText("Search");
        searchObatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchObatButtonActionPerformed(evt);
            }
        });
        jPanel6.add(searchObatButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 91, 30));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel11.setText("Id Obat");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 310, 80, 30));
        jPanel6.add(searchObatField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 170, 30));

        jButton10.setText("Refresh");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 91, 30));

        panePage.addTab("tab5", jPanel6);

        getContentPane().add(panePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, -37, 710, 840));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1)
        {
            panePage.setSelectedIndex(2);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jTextField_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usernameActionPerformed

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1)
        {
            panePage.setSelectedIndex(4);
        }
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1)
        {
            panePage.setSelectedIndex(3);
        }
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1)
        {
            panePage.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1)
        {
            panePage.setSelectedIndex(1);
        }
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        Pegawai peg = new Pegawai();
        peg.setId(jTextField_id.getText());
        peg.setNama(jTextField_nama.getText());
        peg.setAlamat(jTextField_alamat.getText());
        peg.setContact(jTextField_contact.getText());
        peg.setUsername(jTextField_username.getText());
        peg.setPassword(jTextField_password.getText());
        peg.setKode("2");
        peg.insertPegawai();
        JOptionPane.showMessageDialog(null, "Insert Success");
        jTextField_id.setText(null);
        jTextField_nama.setText(null);
        jTextField_alamat.setText(null);
        jTextField_contact.setText(null);
        jTextField_username.setText(null);
        jTextField_password.setText(null);
        tampilkan();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        jTextField_id.setText(null);
        jTextField_nama.setText(null);
        jTextField_alamat.setText(null);
        jTextField_contact.setText(null);
        jTextField_username.setText(null);
        jTextField_password.setText(null);     
    }//GEN-LAST:event_jButton17ActionPerformed

    private void updatePegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePegawaiButtonActionPerformed
        // TODO add your handling code here:
        editIdPegawaiField.setEnabled(false);
        editNamaPegawaiField.setEnabled(false);
        editAlamatPegawaiField.setEnabled(false);
        editContactPegawaiField.setEnabled(false);
        editUsernamePegawaiField.setEnabled(false);
        editPasswordPegawaiField.setEnabled(false);

        Pegawai peg = new Pegawai();
        peg.setId(editIdPegawaiField.getText());
        peg.setNama(editNamaPegawaiField.getText());
        peg.setAlamat(editAlamatPegawaiField.getText());
        peg.setContact(editContactPegawaiField.getText());
        peg.setUsername(editUsernamePegawaiField.getText());
        peg.setPassword(editPasswordPegawaiField.getText());
        peg.setKode("2");
        peg.updatePegawai();
        
        javax.swing.JOptionPane.showMessageDialog(null, "Update Success");
        
        editIdPegawaiField.setText("");
        editNamaPegawaiField.setText("");
        editAlamatPegawaiField.setText("");
        editContactPegawaiField.setText("");
        editUsernamePegawaiField.setText("");
        editPasswordPegawaiField.setText("");

        editNamaPegawaiField.setEnabled(false);
        editAlamatPegawaiField.setEnabled(false);
        editContactPegawaiField.setEnabled(false);
        editUsernamePegawaiField.setEnabled(false);
        editPasswordPegawaiField.setEnabled(false);
        updatePegawaiButton.setEnabled(false);
        cancelPegawaiButton.setEnabled(false);
        deletePegawaiButton.setEnabled(false);
        tampilkan();        
    }//GEN-LAST:event_updatePegawaiButtonActionPerformed

    private void deletePegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePegawaiButtonActionPerformed
        // TODO add your handling code here:
        editIdPegawaiField.setEnabled(false);
        editNamaPegawaiField.setEnabled(false);
        editAlamatPegawaiField.setEnabled(false);
        editContactPegawaiField.setEnabled(false);
        editUsernamePegawaiField.setEnabled(false);
        editPasswordPegawaiField.setEnabled(false);

        Pegawai peg = new Pegawai();
        peg.setId(editIdPegawaiField.getText());
        peg.setNama(editNamaPegawaiField.getText());
        peg.setAlamat(editAlamatPegawaiField.getText());
        peg.setContact(editContactPegawaiField.getText());
        peg.setUsername(editUsernamePegawaiField.getText());
        peg.setPassword(editPasswordPegawaiField.getText());
        peg.setKode("2");
        peg.deletePegawai();

        javax.swing.JOptionPane.showMessageDialog(null, "Delete Success");

        editIdPegawaiField.setText("");
        editNamaPegawaiField.setText("");
        editAlamatPegawaiField.setText("");
        editContactPegawaiField.setText("");
        editUsernamePegawaiField.setText("");
        editPasswordPegawaiField.setText("");

        editNamaPegawaiField.setEnabled(false);
        editAlamatPegawaiField.setEnabled(false);
        editContactPegawaiField.setEnabled(false);
        editUsernamePegawaiField.setEnabled(false);
        editPasswordPegawaiField.setEnabled(false);
        updatePegawaiButton.setEnabled(false);
        cancelPegawaiButton.setEnabled(false);
        deletePegawaiButton.setEnabled(false);
        tampilkan();
    }//GEN-LAST:event_deletePegawaiButtonActionPerformed

    private void cancelPegawaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPegawaiButtonActionPerformed
        // TODO add your handling code here:
        editIdPegawaiField.setText("");
        editNamaPegawaiField.setText("");
        editAlamatPegawaiField.setText("");
        editContactPegawaiField.setText("");
        editUsernamePegawaiField.setText("");
        editPasswordPegawaiField.setText("");

        editNamaPegawaiField.setEnabled(false);
        editAlamatPegawaiField.setEnabled(false);
        editContactPegawaiField.setEnabled(false);
        editUsernamePegawaiField.setEnabled(false);
        editPasswordPegawaiField.setEnabled(false);
        updatePegawaiButton.setEnabled(false);
        cancelPegawaiButton.setEnabled(false);
        deletePegawaiButton.setEnabled(false);
    }//GEN-LAST:event_cancelPegawaiButtonActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        Obat ob = new Obat();
        ob.setId(jTextField_id3.getText());
        ob.setNama(jTextField_namaobat.getText());
        ob.setHarga(jTextField_harga.getText());
        ob.setStok(jTextField_stok.getText());
        ob.insertObat();

        JOptionPane.showMessageDialog(null, "Insert Success");
        jTextField_id3.setText(null);
        jTextField_namaobat.setText(null);
        jTextField_harga.setText(null);
        jTextField_stok.setText(null);
        tampilkan();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        jTextField_id3.setText(null);
        jTextField_namaobat.setText(null);
        jTextField_harga.setText(null);
        jTextField_stok.setText(null);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void updateObatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateObatButtonActionPerformed
        // TODO add your handling code here:
        Obat ob = new Obat();
        ob.setId(editIdObatField.getText());
        ob.setNama(editNamaObatField.getText());
        ob.setHarga(editHargaObatField.getText());
        ob.setStok(editStokObatField.getText());
        ob.updateObat();
        JOptionPane.showMessageDialog(null, "Update Success");
        
        editIdObatField.setText("");
        editNamaObatField.setText("");
        editHargaObatField.setText("");
        editStokObatField.setText("");                

        editNamaObatField.setEnabled(false);
        editHargaObatField.setEnabled(false);
        editStokObatField.setEnabled(false);                
        updateObatButton.setEnabled(false);
        cancelObatButton.setEnabled(false);
        deleteObatButton.setEnabled(false);
        tampilkan();
    }//GEN-LAST:event_updateObatButtonActionPerformed

    private void deleteObatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteObatButtonActionPerformed
        // TODO add your handling code here:
        editIdObatField.setEnabled(false);
        editNamaObatField.setEnabled(false);
        editHargaObatField.setEnabled(false);
        editStokObatField.setEnabled(false);

        Obat ob = new Obat();
        ob.setId(editIdObatField.getText());
        ob.setNama(editNamaObatField.getText());
        ob.setHarga(editHargaObatField.getText());
        ob.setStok(editStokObatField.getText());
        ob.deleteObat();

        JOptionPane.showMessageDialog(null, "Delete Success");

        editIdObatField.setText("");
        editNamaObatField.setText("");
        editHargaObatField.setText("");
        editStokObatField.setText("");                

        editNamaObatField.setEnabled(false);
        editHargaObatField.setEnabled(false);
        editStokObatField.setEnabled(false);                
        updateObatButton.setEnabled(false);
        cancelObatButton.setEnabled(false);
        deleteObatButton.setEnabled(false);
        tampilkan();
    }//GEN-LAST:event_deleteObatButtonActionPerformed

    private void cancelObatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelObatButtonActionPerformed
        // TODO add your handling code here:
        editIdObatField.setText("");
        editNamaObatField.setText("");
        editHargaObatField.setText("");
        editStokObatField.setText("");                

        editNamaObatField.setEnabled(false);
        editHargaObatField.setEnabled(false);
        editStokObatField.setEnabled(false);                
        updateObatButton.setEnabled(false);
        cancelObatButton.setEnabled(false);
        deleteObatButton.setEnabled(false);
    }//GEN-LAST:event_cancelObatButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        tampilkan();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < dataPegawaiTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataPegawaiTable.getColumnCount(); j++)
            {
                dataPegawaiTable.setValueAt("", i, j);
            }
        }
        
        String id = searchPegawaiField.getText();
        
        ResultSet hasil = pegawai.searchPegawai(id);
        
        try {
            while (hasil.next())
            {
                dataPegawaiTable.setValueAt(hasil.getString(1), 0, 0);
                dataPegawaiTable.setValueAt(hasil.getString(2), 0, 1);
                dataPegawaiTable.setValueAt(hasil.getString(3), 0, 2);
                dataPegawaiTable.setValueAt(hasil.getString(4), 0, 3);
                dataPegawaiTable.setValueAt(hasil.getString(5), 0, 4);
                dataPegawaiTable.setValueAt(hasil.getString(6), 0, 5);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void dataPegawaiTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataPegawaiTableMouseClicked
        // TODO add your handling code here:
        try 
        {
            if (evt.getClickCount() == 2)
            {
                int row = dataPegawaiTable.getSelectedRow();

                editIdPegawaiField.setText(dataPegawaiTable.getValueAt(row, 0).toString());
                editNamaPegawaiField.setText(dataPegawaiTable.getValueAt(row, 1).toString());
                editAlamatPegawaiField.setText(dataPegawaiTable.getValueAt(row, 2).toString());
                editContactPegawaiField.setText(dataPegawaiTable.getValueAt(row, 3).toString());
                editUsernamePegawaiField.setText(dataPegawaiTable.getValueAt(row, 4).toString());
                editPasswordPegawaiField.setText(dataPegawaiTable.getValueAt(row, 5).toString());

                editNamaPegawaiField.setEnabled(true);
                editAlamatPegawaiField.setEnabled(true);
                editContactPegawaiField.setEnabled(true);
                editUsernamePegawaiField.setEnabled(true);
                editPasswordPegawaiField.setEnabled(true);
                updatePegawaiButton.setEnabled(true);
                cancelPegawaiButton.setEnabled(true);
                deletePegawaiButton.setEnabled(true);
            }
        } 
        catch (Throwable t)
        {
            JOptionPane.showMessageDialog(rootPane, "Field yang dipilih kosong!", "Error", 2);
        }
    }//GEN-LAST:event_dataPegawaiTableMouseClicked

    private void dataObatTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataObatTableMouseClicked
        // TODO add your handling code here:
        try 
        {
            if (evt.getClickCount() == 2)
            {
                int row = dataObatTable.getSelectedRow();

                editIdObatField.setText(dataObatTable.getValueAt(row, 0).toString());
                editNamaObatField.setText(dataObatTable.getValueAt(row, 1).toString());
                editHargaObatField.setText(dataObatTable.getValueAt(row, 2).toString());
                editStokObatField.setText(dataObatTable.getValueAt(row, 3).toString());                

                editNamaObatField.setEnabled(true);
                editHargaObatField.setEnabled(true);
                editStokObatField.setEnabled(true);                
                updateObatButton.setEnabled(true);
                cancelObatButton.setEnabled(true);
                deleteObatButton.setEnabled(true);
            }
        } 
        catch (Throwable t)
        {
            JOptionPane.showMessageDialog(rootPane, "Field yang dipilih kosong!", "Error", 2);
        }
    }//GEN-LAST:event_dataObatTableMouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        tampilkan();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void searchObatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchObatButtonActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < dataObatTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataObatTable.getColumnCount(); j++)
            {
                dataObatTable.setValueAt("", i, j);
            }
        }
        
        String id = searchObatField.getText();
        
        ResultSet hasilObat = obat.searchObat(id);
        
        try {
            while (hasilObat.next())
            {
                dataObatTable.setValueAt(hasilObat.getString(1), 0, 0);
                dataObatTable.setValueAt(hasilObat.getString(2), 0, 1);
                dataObatTable.setValueAt(hasilObat.getString(3), 0, 2);
                dataObatTable.setValueAt(hasilObat.getString(4), 0, 3);  
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchObatButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LoginForm lp = new LoginForm();
        lp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tampilkan()
    {
        for (int i = 0; i < dataPegawaiTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataPegawaiTable.getColumnCount(); j++)
            {
                dataPegawaiTable.setValueAt("", i, j);
            }
        }
        
        ResultSet hasil = pegawai.getPegawai();
        int row = 0;
        
        try {
            while (hasil.next())
            {
                dataPegawaiTable.setValueAt(hasil.getString(1), row, 0);
                dataPegawaiTable.setValueAt(hasil.getString(2), row, 1);
                dataPegawaiTable.setValueAt(hasil.getString(3), row, 2);
                dataPegawaiTable.setValueAt(hasil.getString(4), row, 3);
                dataPegawaiTable.setValueAt(hasil.getString(5), row, 4);
                dataPegawaiTable.setValueAt(hasil.getString(6), row, 5);
                
                row++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (int i = 0; i < dataObatTable.getRowCount(); i++)
        {
            for (int j = 0; j < dataObatTable.getColumnCount(); j++)
            {
                dataObatTable.setValueAt("", i, j);
            }
        }
        
        ResultSet hasilObat = obat.getObat();
        int rowObat = 0;
        
        try {
            while (hasilObat.next())
            {
                dataObatTable.setValueAt(hasilObat.getString(1), rowObat, 0);
                dataObatTable.setValueAt(hasilObat.getString(2), rowObat, 1);
                dataObatTable.setValueAt(hasilObat.getString(3), rowObat, 2);
                dataObatTable.setValueAt(hasilObat.getString(4), rowObat, 3);                
                
                rowObat++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
            
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelObatButton;
    private javax.swing.JButton cancelPegawaiButton;
    private javax.swing.JTable dataObatTable;
    private javax.swing.JTable dataPegawaiTable;
    private javax.swing.JButton deleteObatButton;
    private javax.swing.JButton deletePegawaiButton;
    private javax.swing.JTextField editAlamatPegawaiField;
    private javax.swing.JTextField editContactPegawaiField;
    private javax.swing.JTextField editHargaObatField;
    private javax.swing.JTextField editIdObatField;
    private javax.swing.JTextField editIdPegawaiField;
    private javax.swing.JTextField editNamaObatField;
    private javax.swing.JTextField editNamaPegawaiField;
    private javax.swing.JTextField editPasswordPegawaiField;
    private javax.swing.JTextField editStokObatField;
    private javax.swing.JTextField editUsernamePegawaiField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField_alamat;
    private javax.swing.JTextField jTextField_contact;
    private javax.swing.JTextField jTextField_harga;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_id3;
    private javax.swing.JTextField jTextField_nama;
    private javax.swing.JTextField jTextField_namaobat;
    private javax.swing.JTextField jTextField_password;
    private javax.swing.JTextField jTextField_stok;
    private javax.swing.JTextField jTextField_username;
    private javax.swing.JTabbedPane panePage;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton searchObatButton;
    private javax.swing.JTextField searchObatField;
    private javax.swing.JTextField searchPegawaiField;
    private javax.swing.JButton updateObatButton;
    private javax.swing.JButton updatePegawaiButton;
    // End of variables declaration//GEN-END:variables
}
