/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package drugmacy;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.*;
import java.sql.ResultSet;
import drugmacy.Package.Connector;

/**
 *
 * @author nurka
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginForm() {
        initComponents();
    }
    
    class JPanelGradient extends javax.swing.JPanel
    {
        protected void paintComponent(Graphics g)
        {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
            
            Color color1 = new Color(0, 51, 102);
            Color color2 = new Color(0, 204, 153);
            GradientPaint gp = new GradientPaint(0, 0, color1, width, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanelGradient();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField_password = new javax.swing.JPasswordField();
        jButton_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jPanel1.setBackground(new java.awt.Color(51, 102, 0));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 150, 138));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, 46));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 105, -1));

        jTextField_username.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel1.add(jTextField_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 320, 30));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        jPasswordField_password.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel1.add(jPasswordField_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 320, 30));

        jButton_login.setText("Login");
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
        // TODO add your handling code here:
            if (jTextField_username.getText().equals("") && jPasswordField_password.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please Complete the Fields");
        } else if (jTextField_username.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please Complete the Username Field");
        } else if (jPasswordField_password.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please Complete the Password Field");
        } else {
            Connector kon = new Connector();
            ResultSet rs = null;

            try {
                rs = kon.getData("select * from pegawai where username = '"
                        + jTextField_username.getText() + "' and password = '"
                        + jPasswordField_password.getText() + "' and kode = '1'");

                if (rs.next()) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Login Success");
                    AdminPage adm = new AdminPage();
                    adm.setVisible(true);
                    dispose();
                    jTextField_username.setEnabled(false);
                    jPasswordField_password.setEnabled(false);
                    jButton_login.setEnabled(false);
                } else {
                    // If no result for admin, check for user login
                    rs = kon.getData("select * from pegawai where username = '"
                            + jTextField_username.getText() + "' and password = '"
                            + jPasswordField_password.getText() + "' and kode = '2'");

                    if (rs.next()) {
                        javax.swing.JOptionPane.showMessageDialog(null, "Login Success");
                        UserPage us = new UserPage();
                        us.setVisible(true);
                        dispose();
                        jTextField_username.setEnabled(false);
                        jPasswordField_password.setEnabled(false);
                        jButton_login.setEnabled(false);
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(null, "Invalid Username or Password");
                    }
                }
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            } finally {
                try {
                    if (rs != null) {
                        rs.close();
                    }
                } catch (Exception e) {
                    // Handle the exception, if needed
                }
            }
        }

    }//GEN-LAST:event_jButton_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
